Added a new GitHub action to clean terraform state

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -69,6 +69,15 @@ jobs:
           fi
       working-directory: nodejs-hello-world
 
+    - name: Terraform State Cleanup (Optional)
+      env:
+        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+      run: |
+        terraform state rm module.network || echo "Resource not found in state"
+      
     - name: Terraform Import Resources
       env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
