Added GitHub action to remove stale plan

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,6 +34,12 @@ jobs:
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
 
+    - name: Clean Up Stale Plan Files and State Lock
+      run: |
+          rm -f tfplan
+          terraform force-unlock -force 0 || true
+      working-directory: nodejs-hello-world
+
     - name: Terraform Init
       env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
@@ -43,16 +49,19 @@ jobs:
       run: terraform init
       working-directory: nodejs-hello-world
 
-    #Added configuration for Terraform State Remove
-#    - name: Terraform State Remove
-#      run: |
-#        terraform state rm module.network
-#      terraform state rm module.network.azurerm_resource_group.rg
-#      terraform state rm module.network.azurerm_public_ip.frontend_pip
-#      terraform state rm module.network.azurerm_network_security_group.frontend_nsg
-#      terraform state rm module.network.azurerm_virtual_network.vnet
-#      working-directory: nodejs-hello-world
-  
+    - name: Terraform State Cleanup (Optional)
+      env:
+        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+      run: |
+        terraform state rm module.network.azurerm_virtual_network.vnet || echo "Resource not found in state"
+        terraform state rm module.network.azurerm_network_security_group.frontend_nsg || echo "Resource not found in state"
+        terraform state rm module.network.azurerm_public_ip.frontend_pip || echo "Resource not found in state"
+        terraform state rm module.network.aazurerm_subnet.frontend || echo "Resource not found in state"
+      working-directory: nodejs-hello-world
+
     - name: Terraform Plan
       env:
           ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
@@ -68,32 +77,20 @@ jobs:
             exit 1
           fi
       working-directory: nodejs-hello-world
-
-    - name: Terraform State Cleanup (Optional)
-      env:
-        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-      run: |
-        terraform state rm module.network.azurerm_virtual_network.vnet || echo "Resource not found in state"
-        terraform state rm module.network.azurerm_network_security_group.frontend_nsg || echo "Resource not found in state"
-        terraform state rm module.network.azurerm_public_ip.frontend_pip || echo "Resource not found in state"
-        terraform state rm module.network.aazurerm_subnet.frontend || echo "Resource not found in state"
-      
-    - name: Terraform Import Resources
-      env:
-          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-      run: | 
-        terraform import module.network.azurerm_resource_group.rg /subscriptions/***/resourceGroups/iac-secure-rg
+   
+#    - name: Terraform Import Resources
+#      env:
+#          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+#          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+#          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+#          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+#      run: | 
+#        terraform import module.network.azurerm_resource_group.rg /subscriptions/***/resourceGroups/iac-secure-rg
 #       terraform import module.network.azurerm_virtual_network.vnet "/subscriptions/7c63e1b6-0a9a-487e-b657-e58721d3e957/resourceGroups/iac-secure-rg/providers/Microsoft.Network/virtualNetworks/iac-vnet"
 #       terraform import module.network.azurerm_network_security_group.frontend_nsg "/subscriptions/7c63e1b6-0a9a-487e-b657-e58721d3e957/resourceGroups/iac-secure-rg/providers/Microsoft.Network/networkSecurityGroups/frontend-nsg"
 #       terraform import module.network.azurerm_public_ip.frontend_pip "/subscriptions/7c63e1b6-0a9a-487e-b657-e58721d3e957/resourceGroups/iac-secure-rg/providers/Microsoft.Network/publicIPAddresses/frontend-pip"
 #       terraform import module.network.azurerm_subnet.frontend "/subscriptions/7c63e1b6-0a9a-487e-b657-e58721d3e957/resourceGroups/iac-secure-rg/providers/Microsoft.Network/virtualNetworks/iac-vnet/subnets/frontend-subnet"
-      working-directory: nodejs-hello-world
+#      working-directory: nodejs-hello-world
 
     - name: Terraform Apply
       env:
