Added config to validate the plan state

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,7 +59,15 @@ jobs:
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
-      run: terraform plan -out=tfplan
+      run: |
+        |
+          terraform plan -out=tfplan
+          if [ -f tfplan ]; then
+            echo "Plan file created successfully."
+          else
+            echo "Plan file not found. Exiting."
+            exit 1
+          fi
       working-directory: nodejs-hello-world
 
     - name: Terraform Import Resources
@@ -81,7 +89,14 @@ jobs:
           ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
           ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
           ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-      run: terraform apply -auto-approve tfplan
+      run: |
+        |
+          if [ -f tfplan ]; then
+            terraform apply -auto-approve tfplan
+          else
+            echo "No plan file found to apply."
+            exit 1
+          fi
       working-directory: nodejs-hello-world
 
     - name: Verify Deployment
